# 詳細については、Dockerfile.debianのコメントを参照。
FROM --platform=$BUILDPLATFORM node:24.18.0-alpine3.23 AS client-builder
COPY client/package*.json /app/client/
WORKDIR /app/client
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY . /app/
RUN npm run build --loglevel=info

FROM node:24.18.0-alpine3.23 AS server-builder
RUN apk add --no-cache g++ git make pkgconf python3
WORKDIR /app
COPY package*.json /app/
ENV DOCKER="YES"
RUN npm config set fetch-retries 10 \
    && npm config set fetch-retry-mintimeout 100000 \
    && npm config set fetch-retry-maxtimeout 600000
RUN npm install --no-save --loglevel=info
COPY . .
RUN rm -rf client
RUN npm run update-tsreadex
RUN npm run build-server --loglevel=info

FROM node:24.18.0-alpine3.23
LABEL maintainer="l3tnun"
RUN apk add --no-cache ffmpeg \
    && ln -sf /usr/bin/ffmpeg /usr/local/bin/ffmpeg \
    && ln -sf /usr/bin/ffprobe /usr/local/bin/ffprobe
ENV NEOEPGSTATION_CONTAINER_RUNTIME=docker
COPY --from=server-builder /app /app/
COPY --from=client-builder /app/client /app/client/
EXPOSE 8888
WORKDIR /app
ENTRYPOINT ["npm"]
CMD ["start"]
